### ISSUE TITLE
Differences with virtualgo?

### ISSUE THREAD

**Issue by erichulburd** [pshirali/vgo#2]
I definitely appreciate the effort to improve go package management - it's definitely a battle!

Wondering if you have used [virtualgo](https://github.com/GetStream/vg) and what the important differences are? From the looks of it, it looks like a very similar approach and I can personally say virtualgo has been a big productivity booster for me.

**Comment by pshirali** [comment]
@erichulburd , thanks for dropping in. No, I haven't used `virtualgo`, so, I'm not really in an ideal position to give you a fair comparison between the two.

vGo aims to solve only two problems:
1. Manage/switch between working on multiple repos as private workspaces (subshell and populate go envs as you enter and exit workspaces)
1. Have a way for a go-developer to extend functionality by adding in additional commands as bash-functions. (example: define custom commands for commonly invoked set of tasks, tie in a particular version of golang for a specific repo, etc). What you do here is totally upto you.

Because it only aims to solve these bare-essential problems, it's just one shell-script that you can copy over to any vanilla machine and run. The only thing expected by vGo is that you maintain all workspaces from within one parent folder. The full documentation for vGo is just the README file.

vGo works very well for me. I tend to develop across multiple machines, and often hack around code via terminal. I wrote vGo with a minimalist approach, and it has helped me well. I've not felt the need to look into other tools yet.

Note: vGo does not do package/dependency management. You are free to use whatever method you like (ex: `glide`) for managing packages and their versions.

**Comment by pshirali** [comment]
@erichulburd do you have any follow up questions or comments? If you are satisfied, can I close this issue?
